# base_url = "http://qaboy.com/"
base_url = "https://dev.firstbuy.com/"
trending_url = "https://dev.firstbuy.com/trending/"
deals_url = "https://dev.firstbuy.com/deals/"
cart_url = "https://dev.firstbuy.com/cart/"
login_url = "http://localhost:8000/login/?next=/"
